name = "Somitaw Adventure Pack"
author = "somitadepony"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea252b44273736652012162f27e361f842cc49ac409bc7390364349015be31f1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
