name = "Somitaw Adventure Pack"
author = "somitadepony"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10c2888bfecec6f99b31bbbbb98933f3f567f75caa3a20bfe494e4be20e69a14"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
