name = "Somitaw Adventure Pack"
author = "somitadepony"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cdc67a2de09f0e57c07130e78c6c05522a1e0be711346d08a10cb1430eae2fa"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
